apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjM0JsZEhKMWF6cG5hSEJmVFZGRVRuQTFTREZ3UjFBNVpYaHpWVVpEUmtsS1NrUnVUVUZCUXpZMU1XSmhPVk5uIgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
